{"level":"error","message":"MongoDB Connection Error: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":2208032793,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\ceo\\Desktop\\Finance\\backend\\node_modules\\mongoose\\lib\\connection.js:1089:11)\n    at NativeConnection.openUri (C:\\Users\\ceo\\Desktop\\Finance\\backend\\node_modules\\mongoose\\lib\\connection.js:1040:11)\n    at async connectDB (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\config\\database.js:6:5)","timestamp":"2024-12-15T06:00:04.514Z"}
{"level":"error","message":"MongoDB Connection Error: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":2208085629,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\ceo\\Desktop\\Finance\\backend\\node_modules\\mongoose\\lib\\connection.js:1089:11)\n    at NativeConnection.openUri (C:\\Users\\ceo\\Desktop\\Finance\\backend\\node_modules\\mongoose\\lib\\connection.js:1040:11)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:540:9)\n    at process.processTimers (node:internal/timers:514:7)\n    at async connectDB (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\config\\database.js:6:5)","timestamp":"2024-12-15T06:00:57.349Z"}
{"level":"error","message":"MongoDB Connection Error: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":2208155497,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\ceo\\Desktop\\Finance\\backend\\node_modules\\mongoose\\lib\\connection.js:1089:11)\n    at NativeConnection.openUri (C:\\Users\\ceo\\Desktop\\Finance\\backend\\node_modules\\mongoose\\lib\\connection.js:1040:11)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:540:9)\n    at process.processTimers (node:internal/timers:514:7)\n    at async connectDB (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\config\\database.js:6:5)","timestamp":"2024-12-15T06:02:07.234Z"}
{"level":"error","message":"Registration error: User already exists","stack":"Error: User already exists\n    at AuthService.registerUser (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\services\\authService.js:14:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AuthController.register (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\controllers\\authController.js:13:22)","timestamp":"2024-12-15T11:56:21.110Z"}
{"level":"error","message":"Login error: Please verify your account with OTP first","stack":"Error: Please verify your account with OTP first\n    at AuthService.login (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\services\\authService.js:75:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AuthController.login (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\controllers\\authController.js:46:22)","timestamp":"2024-12-15T11:57:37.514Z"}
{"level":"error","message":"Registration error: User already exists","stack":"Error: User already exists\n    at AuthService.registerUser (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\services\\authService.js:14:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AuthController.register (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\controllers\\authController.js:13:22)","timestamp":"2024-12-15T13:57:07.751Z"}
{"level":"error","message":"Login error: Invalid credentials","stack":"Error: Invalid credentials\n    at AuthService.login (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\services\\authService.js:101:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AuthController.login (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\controllers\\authController.js:46:22)","timestamp":"2024-12-15T14:55:45.385Z"}
{"level":"error","message":"Login error: Invalid credentials","stack":"Error: Invalid credentials\n    at AuthService.login (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\services\\authService.js:101:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AuthController.login (C:\\Users\\ceo\\Desktop\\Finance\\backend\\src\\controllers\\authController.js:46:22)","timestamp":"2024-12-15T14:55:48.875Z"}
{"level":"error","message":"MongoDB Connection Error: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"boltfinanacecluster-shard-00-00.bxd3l.mongodb.net:27017":{"$clusterTime":null,"address":"boltfinanacecluster-shard-00-00.bxd3l.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":182036697,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"boltfinanacecluster-shard-00-01.bxd3l.mongodb.net:27017":{"$clusterTime":null,"address":"boltfinanacecluster-shard-00-01.bxd3l.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":182036635,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"boltfinanacecluster-shard-00-02.bxd3l.mongodb.net:27017":{"$clusterTime":null,"address":"boltfinanacecluster-shard-00-02.bxd3l.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":182036625,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-9vy089-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (/Users/AshwinSevak/Desktop/Ashwin-Sevak/Bolt-Finance-Backend-Development/node_modules/mongoose/lib/connection.js:1089:11)\n    at NativeConnection.openUri (/Users/AshwinSevak/Desktop/Ashwin-Sevak/Bolt-Finance-Backend-Development/node_modules/mongoose/lib/connection.js:1040:11)\n    at async connectDB (/Users/AshwinSevak/Desktop/Ashwin-Sevak/Bolt-Finance-Backend-Development/src/config/database.js:6:5)","timestamp":"2024-12-18T14:27:10.264Z"}
